openapi: 3.0.0
info:
  title: Shrink PPTX API
  description: Shrink the images in a PowerPoint presentation
  version: 1.0.0
  contact:
    name: Devin Atkin
    email: devin@graphconstructor.com
servers:
  - url: https://shrink.graphconstructor.com
paths:
  /shrink_pptx:
    post:
      summary: Shrink the images in a PowerPoint presentation
      operationId: shrinkPptx
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: The shrunk PowerPoint presentation
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary